apiVersion: apps/v1
kind: Deployment
metadata:
  name: kbv
  labels:
    app: kbv
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
      - name: kbv-app
        image: ifilyaninitmo/itdt-contained-frontend:master
        ports:
        - containerPort: 9000
        env:
        - name: REACT_APP_USERNAME
          value: "User1"
        - name: REACT_APP_COMPANY_NAME
          value: "ITMO"
